### PR TITLE
Add labels and data

### PR DESCRIPTION
**Pull request by neekfenwick**
Added new features for label rendering and arbitrary data associated with Rectangles.

### CODE REVIEW

**Comment by neekfenwick** [comment]
This resolves Issue #5 .. I can't see how to link this PR to that Issue.

**Comment by neekfenwick** [comment]
My local git has screwed up the 'author' of the two most recent commits, they are neek@localhost.localdomain.. but I guess this doesn't matter, you could still accept this PR and it still seems to be linked to my github account.  I guess there may be some tidying to do with the version number in package.json.

**Comment by neekfenwick** [comment]
Just checking up .. no response for a while, I presume you're on holiday over Christmas? Hope you're having a good one :) No rush here, we're fine running the dev version of the module.

**Comment by dagmike** [comment]
Hi man, yeah sorry been taking a break away from work and computers for the
holiday season but I'm back next week so I'll be able to take a look then.

**Comment by neekfenwick** [comment]
We had an annoying requirement from our team for the new Linear layout algorithm, where items are arranged 1 dimensionally left to right.  Apparently our print team actually line up the products so everything on one bed is aligned to the top edge of the tallest item.  I think it's a quirk of their printing software.  As a workaround, they can take the layout presented, where all items are aligned with y == 0 i.e. the bottom edges are all at the bottom of the bed, and just fudge it in the real world to align those top edges.  From looking at the algorithm code it looks really annoying to try to achieve that, given that it's a static method with no real sense of before and after.  I wonder if you have any ideas, not that it's your problem but maybe with your longer knowledge of the problem space you can throw out something :)

**Comment by neekfenwick** [comment]
While waiting for your review of the PR I've come up with an improvement.  The labels are currently rendered rather dumbly, and if they are wider than the Rectangle then they overlap off the sides.  I'm now working on line wrapping, using `queryFontMetrics` to measure each line of text and chop the label up with "\n" if any line is too long.  This keeps the label within the rect width quite nicely.  Watch this space..

**Comment by neekfenwick** [comment]
I don't know github very well but it looks like my two recent commits have appears on this PR, so I don't need to update anything further.  So long as you're looking at the latest commit "Employ word wrapping...." then we're good.  I also fixed a small offset error in the label position that existed in my original commits, because I hadn't taken the margin into account.

**Review by dagmike — COMMENTED** [review]
Hi, really sorry its taken me this long to loo at this, I've had my hands full at work. All the changes look great, hopefully I'll get more time to play around with them soon. Cheers

**Comment by dagmike** [comment]
Re the linear layout requirement I'm not too sure to be honest. The algorithms are simply a port of a C++ library (linked in the readme). 

We use the algorithms at my place of work in order to get the maximum amount of rectangles into a larger rectangle. We make picture frames so we have to cut larger sheets of say glass into smaller pieces to go into the picture frames, so our requirements are simple just to fit as many rectangles as possible into a restricted size, the alignment of them is not of any importance to us.

Sorry I couldn't help any further, hope you can figure it all out, cheers.

**Pull request merged**
